In [2]:
import numpy as np
import time 

In [3]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [4]:
#check the speed of vectorization against for loops
a = np.random.rand(1000000)
b = np.random.rand(1000000)

tic = time.time()
c = np.dot(a,b)
toc = time.time()

print (c)
print ("vectorization version : " + str (1000*(toc-tic)) + "ms" )

c = 0 
tic = time.time()
for i in range (1000000):
    c += a[i]*b[i]
toc = time.time()

print (c)
print ("for loop : " + str (1000*(toc-tic)) + "ms" )

249787.05528627743
vectorization version : 9.999990463256836ms
249787.0552862723
for loop : 1990.0028705596924ms


In [5]:
#Broadcasting 
A = np.array([[56.0,0.0,4.4,68.0],
              [1.2,104.0,52.0,8.0],
              [1.8,135.0,99.0,0.9]])

print (A)

[[ 56.    0.    4.4  68. ]
 [  1.2 104.   52.    8. ]
 [  1.8 135.   99.    0.9]]


In [6]:
cal = A.sum(axis=0) #to sum vertically

print (cal)

[ 59.  239.  155.4  76.9]


In [8]:
percentage = 100*A/cal.reshape(1,4)

print (percentage)

[[94.91525424  0.          2.83140283 88.42652796]
 [ 2.03389831 43.51464435 33.46203346 10.40312094]
 [ 3.05084746 56.48535565 63.70656371  1.17035111]]
